<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<!--
			Suppress specific warnings that are not relevant for this project:
			- IDE0350: Use collection expression
			- IDE0200: Use pattern matching
			- 1591: Missing XML comment for publicly visible type or member
		-->
		<NoWarn>$(NoWarn), IDE0350, IDE0200, 1591</NoWarn>
	</PropertyGroup>

</Project>
